# -*- coding: utf-8 -*-
$:.unshift('/Library/RubyMotion/lib')
require 'motion/project'
require 'rubygems'
require 'ib'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'Button Fun'
end
